using System;
using FluentNHibernate.Data;

namespace FluentNHibernateClasses.Entities
{
    public class co : Entity
    {
        public virtual Guid RowPointer{ get;set; } 
        public virtual int edi_order{ get;set; } 
        public virtual int use_exch_rate{ get;set; } 
        public virtual int ship_partial{ get;set; } 
        public virtual int ship_early{ get;set; } 
        public virtual int fixed_rate{ get;set; } 
        public virtual int invoiced{ get;set; } 
        public virtual int uf_enduser_flag{ get;set; } 
        public virtual int einvoice{ get;set; } 
        public virtual int logifld{ get;set; } 
        public virtual int InWorkflow{ get;set; } 
        public virtual int include_tax_in_price{ get;set; } 
        public virtual int Uf_LRM_Integrate{ get;set; } 
        public virtual int is_external{ get;set; } 
        public virtual int credit_hold{ get;set; } 
        public virtual int sync_reqd{ get;set; } 
        public virtual int aps_pull_up{ get;set; } 
        public virtual int consolidate{ get;set; } 
        public virtual int summarize{ get;set; } 
        public virtual int NoteExistsFlag{ get;set; } 
        public virtual int qty_packages{ get;set; } 
        public virtual int cust_seq{ get;set; } 
        public virtual int Uf_LRM_Priority{ get;set; } 
        public virtual int Uf_LRM_IntermediateCustSeq{ get;set; } 
        public virtual DateTime order_date{ get;set; } 
        public virtual DateTime close_date{ get;set; } 
        public virtual DateTime eff_date{ get;set; } 
        public virtual DateTime exp_date{ get;set; } 
        public virtual DateTime credit_hold_date{ get;set; } 
        public virtual DateTime projected_date{ get;set; } 
        public virtual DateTime RecordDate{ get;set; } 
        public virtual DateTime datefld{ get;set; } 
        public virtual DateTime CreateDate{ get;set; } 
        public virtual decimal price{ get;set; } 
        public virtual decimal weight{ get;set; } 
        public virtual decimal freight{ get;set; } 
        public virtual decimal misc_charges{ get;set; } 
        public virtual decimal prepaid_amt{ get;set; } 
        public virtual decimal sales_tax{ get;set; } 
        public virtual decimal vovhd_cost_t{ get;set; } 
        public virtual decimal out_cost_t{ get;set; } 
        public virtual decimal exch_rate{ get;set; } 
        public virtual decimal decifld1{ get;set; } 
        public virtual decimal decifld2{ get;set; } 
        public virtual decimal decifld3{ get;set; } 
        public virtual decimal sales_tax_t2{ get;set; } 
        public virtual decimal disc_amount{ get;set; } 
        public virtual decimal disc{ get;set; } 
        public virtual decimal matl_cost_t{ get;set; } 
        public virtual decimal lbr_cost_t{ get;set; } 
        public virtual decimal fovhd_cost_t{ get;set; } 
        public virtual decimal cost{ get;set; } 
        public virtual decimal freight_t{ get;set; } 
        public virtual decimal m_charges_t{ get;set; } 
        public virtual decimal prepaid_t{ get;set; } 
        public virtual decimal sales_tax_t{ get;set; } 
        public virtual decimal sales_tax_2{ get;set; } 
        public virtual string co_num{ get;set; } 
        public virtual string est_num{ get;set; } 
        public virtual string cust_num{ get;set; } 
        public virtual string contact{ get;set; } 
        public virtual string phone{ get;set; } 
        public virtual string cust_po{ get;set; } 
        public virtual string uf_enduser_fax{ get;set; } 
        public virtual string uf_enduser_name{ get;set; } 
        public virtual string uf_enduser_other{ get;set; } 
        public virtual string uf_enduser_phone{ get;set; } 
        public virtual string uf_enduser_state{ get;set; } 
        public virtual string uf_enduser_zip{ get;set; } 
        public virtual string uf_enduser_addr4{ get;set; } 
        public virtual string uf_enduser_city{ get;set; } 
        public virtual string uf_enduser_contact{ get;set; } 
        public virtual string uf_enduser_country{ get;set; } 
        public virtual string uf_enduser_county{ get;set; } 
        public virtual string uf_enduser_email{ get;set; } 
        public virtual string external_confirmation_ref{ get;set; } 
        public virtual string prospect_id{ get;set; } 
        public virtual string opp_id{ get;set; } 
        public virtual string uf_enduser_addr1{ get;set; } 
        public virtual string uf_enduser_addr2{ get;set; } 
        public virtual string uf_enduser_addr3{ get;set; } 
        public virtual string Uf_LRM_FreightTerms{ get;set; } 
        public virtual string Uf_LRM_OnwardCarrier{ get;set; } 
        public virtual string Uf_LRM_OnwardClassOfService{ get;set; } 
        public virtual string Uf_LRM_ShipPo{ get;set; } 
        public virtual string Uf_LRM_ConsigneeShipType{ get;set; } 
        public virtual string Uf_LRM_IntermediateCustNum{ get;set; } 
        public virtual string Uf_LRM_PackListMsg{ get;set; } 
        public virtual string Uf_LRM_ShipmentServices1{ get;set; } 
        public virtual string Uf_LRM_ShipmentServices2{ get;set; } 
        public virtual string Uf_LRM_Carrier{ get;set; } 
        public virtual string Uf_LRM_ClassOfService{ get;set; } 
        public virtual string Uf_LRM_FreightAccount{ get;set; } 
        public virtual string config_id{ get;set; } 
        public virtual string CreatedBy{ get;set; } 
        public virtual string UpdatedBy{ get;set; } 
        public virtual string trans_nat_2{ get;set; } 
        public virtual string apply_to_inv_num{ get;set; } 
        public virtual string Uf_LRM_BOLMsg{ get;set; } 
        public virtual string credit_hold_reason{ get;set; } 
        public virtual string credit_hold_user{ get;set; } 
        public virtual string order_source{ get;set; } 
        public virtual string charfld1{ get;set; } 
        public virtual string charfld2{ get;set; } 
        public virtual string charfld3{ get;set; } 
        public virtual string msc_tax_code1{ get;set; } 
        public virtual string msc_tax_code2{ get;set; } 
        public virtual string pricecode{ get;set; } 
        public virtual string end_user_type{ get;set; } 
        public virtual string orig_site{ get;set; } 
        public virtual string lcr_num{ get;set; } 
        public virtual string process_ind{ get;set; } 
        public virtual string delterm{ get;set; } 
        public virtual string tax_code1{ get;set; } 
        public virtual string tax_code2{ get;set; } 
        public virtual string frt_tax_code1{ get;set; } 
        public virtual string frt_tax_code2{ get;set; } 
        public virtual string taken_by{ get;set; } 
        public virtual string terms_code{ get;set; } 
        public virtual string ship_code{ get;set; } 
        public virtual string slsman{ get;set; } 
        public virtual string whse{ get;set; } 
        public virtual string trans_nat{ get;set; } 
        public virtual string type{ get;set; } 
        public virtual string stat{ get;set; } 
        public virtual string discount_type{ get;set; } 
        public virtual string edi_type{ get;set; } 
        public virtual string convert_type{ get;set; } 
        public virtual string inv_freq{ get;set; } 
        public virtual string ack_stat{ get;set; } 
        public virtual string export_type{ get;set; } 


    }
}