using System;
using FluentNHibernate.Data;

namespace FluentNHibernateClasses.Entities
{
    public class item : Entity
    {
        public virtual Guid RowPointer{ get;set; } 
        public virtual int stocked{ get;set; } 
        public virtual int low_level{ get;set; } 
        public virtual int mps_flag{ get;set; } 
        public virtual int accept_req{ get;set; } 
        public virtual int phantom_flag{ get;set; } 
        public virtual int plan_flag{ get;set; } 
        public virtual int print_kit_components{ get;set; } 
        public virtual int show_in_drop_down_list{ get;set; } 
        public virtual int controlled_by_external_ics{ get;set; } 
        public virtual int active_for_data_integration{ get;set; } 
        public virtual int include_in_net_change_planning{ get;set; } 
        public virtual int uf_plank_item{ get;set; } 
        public virtual int Uf_LRM_IsShipped{ get;set; } 
        public virtual int uf_qc_required{ get;set; } 
        public virtual int kit{ get;set; } 
        public virtual int order_configurable{ get;set; } 
        public virtual int job_configurable{ get;set; } 
        public virtual int InWorkflow{ get;set; } 
        public virtual int mfg_supply_switching_active{ get;set; } 
        public virtual int use_reorder_point{ get;set; } 
        public virtual int tax_free_matl{ get;set; } 
        public virtual int lot_tracked{ get;set; } 
        public virtual int pass_req{ get;set; } 
        public virtual int lot_gen_exp{ get;set; } 
        public virtual int mrp_part{ get;set; } 
        public virtual int infinite_part{ get;set; } 
        public virtual int NoteExistsFlag{ get;set; } 
        public virtual int backflush{ get;set; } 
        public virtual int logifld{ get;set; } 
        public virtual int track_ecn{ get;set; } 
        public virtual int reservable{ get;set; } 
        public virtual int serial_length{ get;set; } 
        public virtual int serial_tracked{ get;set; } 
        public virtual int lead_time{ get;set; } 
        public virtual int suffix{ get;set; } 
        public virtual int days_supply{ get;set; } 
        public virtual int paper_time{ get;set; } 
        public virtual int dock_time{ get;set; } 
        public virtual int next_config{ get;set; } 
        public virtual int safety_stock_rule{ get;set; } 
        public virtual int shelf_life{ get;set; } 
        public virtual int mps_plan_fence{ get;set; } 
        public virtual int due_period{ get;set; } 
        public virtual int exp_lead_time{ get;set; } 
        public virtual int time_fence_rule{ get;set; } 
        public virtual int tax_free_days{ get;set; } 
        public virtual int uf_skid_qty{ get;set; } 
        public virtual int Uf_LRM_ProductAllocationMethod{ get;set; } 
        public virtual DateTime last_inv{ get;set; } 
        public virtual DateTime change_date{ get;set; } 
        public virtual DateTime datefld{ get;set; } 
        public virtual DateTime chg_date{ get;set; } 
        public virtual DateTime RecordDate{ get;set; } 
        public virtual DateTime CreateDate{ get;set; } 
        public virtual DateTime earliest_planned_po_receipt{ get;set; } 
        public virtual DateTime lowdate{ get;set; } 
        public virtual float time_fence_value{ get;set; } 
        public virtual decimal qty_allocjob{ get;set; } 
        public virtual decimal lot_size{ get;set; } 
        public virtual decimal qty_used_ytd{ get;set; } 
        public virtual decimal qty_mfg_ytd{ get;set; } 
        public virtual decimal lst_lot_size{ get;set; } 
        public virtual decimal unit_cost{ get;set; } 
        public virtual decimal rcvd_under_po_qty_tolerance{ get;set; } 
        public virtual decimal unit_insurance_cost{ get;set; } 
        public virtual decimal unit_loc_frt_cost{ get;set; } 
        public virtual decimal cur_insurance_cost{ get;set; } 
        public virtual decimal cur_loc_frt_cost{ get;set; } 
        public virtual decimal safety_stock_percent{ get;set; } 
        public virtual decimal rcvd_over_po_qty_tolerance{ get;set; } 
        public virtual decimal rate_per_day{ get;set; } 
        public virtual decimal order_max{ get;set; } 
        public virtual decimal supply_tolerance_hrs{ get;set; } 
        public virtual decimal var_exp_lead{ get;set; } 
        public virtual decimal reorder_point{ get;set; } 
        public virtual decimal fixed_order_qty{ get;set; } 
        public virtual decimal cur_out_cost{ get;set; } 
        public virtual decimal avg_matl_cost{ get;set; } 
        public virtual decimal avg_lbr_cost{ get;set; } 
        public virtual decimal avg_fovhd_cost{ get;set; } 
        public virtual decimal avg_vovhd_cost{ get;set; } 
        public virtual decimal avg_out_cost{ get;set; } 
        public virtual decimal vovhd_cost{ get;set; } 
        public virtual decimal out_cost{ get;set; } 
        public virtual decimal cur_matl_cost{ get;set; } 
        public virtual decimal cur_lbr_cost{ get;set; } 
        public virtual decimal cur_fovhd_cost{ get;set; } 
        public virtual decimal cur_vovhd_cost{ get;set; } 
        public virtual decimal cur_duty_cost{ get;set; } 
        public virtual decimal cur_freight_cost{ get;set; } 
        public virtual decimal cur_brokerage_cost{ get;set; } 
        public virtual decimal matl_cost{ get;set; } 
        public virtual decimal lbr_cost{ get;set; } 
        public virtual decimal fovhd_cost{ get;set; } 
        public virtual decimal u_ws_price{ get;set; } 
        public virtual decimal unit_mat_cost{ get;set; } 
        public virtual decimal unit_duty_cost{ get;set; } 
        public virtual decimal unit_freight_cost{ get;set; } 
        public virtual decimal unit_brokerage_cost{ get;set; } 
        public virtual decimal cur_mat_cost{ get;set; } 
        public virtual decimal unit_weight{ get;set; } 
        public virtual decimal cur_u_cost{ get;set; } 
        public virtual decimal var_lead{ get;set; } 
        public virtual decimal decifld1{ get;set; } 
        public virtual decimal decifld2{ get;set; } 
        public virtual decimal decifld3{ get;set; } 
        public virtual decimal comp_other{ get;set; } 
        public virtual decimal comp_fixed{ get;set; } 
        public virtual decimal comp_var{ get;set; } 
        public virtual decimal comp_outside{ get;set; } 
        public virtual decimal sub_matl{ get;set; } 
        public virtual decimal shrink_fact{ get;set; } 
        public virtual decimal asm_outside{ get;set; } 
        public virtual decimal comp_setup{ get;set; } 
        public virtual decimal comp_run{ get;set; } 
        public virtual decimal comp_matl{ get;set; } 
        public virtual decimal comp_tool{ get;set; } 
        public virtual decimal comp_fixture{ get;set; } 
        public virtual decimal asm_matl{ get;set; } 
        public virtual decimal asm_tool{ get;set; } 
        public virtual decimal asm_fixture{ get;set; } 
        public virtual decimal asm_other{ get;set; } 
        public virtual decimal asm_fixed{ get;set; } 
        public virtual decimal asm_var{ get;set; } 
        public virtual decimal lst_u_cost{ get;set; } 
        public virtual decimal avg_u_cost{ get;set; } 
        public virtual decimal order_min{ get;set; } 
        public virtual decimal order_mult{ get;set; } 
        public virtual decimal asm_setup{ get;set; } 
        public virtual decimal asm_run{ get;set; } 
        public virtual string rcpt_rqmt{ get;set; } 
        public virtual string itemID{ get;set; } 
        public virtual string description{ get;set; } 
        public virtual string u_m{ get;set; } 
        public virtual string drawing_nbr{ get;set; } 
        public virtual string product_code{ get;set; } 
        public virtual string job{ get;set; } 
        public virtual string Uf_LRM_UPCCode{ get;set; } 
        public virtual string Uf_LRM_HSTariff{ get;set; } 
        public virtual string Uf_LRM_NetCost{ get;set; } 
        public virtual string Uf_LRM_NMFC{ get;set; } 
        public virtual string Uf_LRM_NMFCSub{ get;set; } 
        public virtual string Uf_LRM_PrefCriterion{ get;set; } 
        public virtual string Uf_LRM_Producer{ get;set; } 
        public virtual string tariff_classification{ get;set; } 
        public virtual string Uf_ItemDescription2{ get;set; } 
        public virtual string uf_label_type{ get;set; } 
        public virtual string uf_pick_zone{ get;set; } 
        public virtual string Uf_LRM_CountryOfOrigin{ get;set; } 
        public virtual string Uf_LRM_Eccn{ get;set; } 
        public virtual string cfg_model{ get;set; } 
        public virtual string co_post_config{ get;set; } 
        public virtual string job_post_config{ get;set; } 
        public virtual string setupgroup{ get;set; } 
        public virtual string CreatedBy{ get;set; } 
        public virtual string UpdatedBy{ get;set; } 
        public virtual string supply_site{ get;set; } 
        public virtual string prod_mix{ get;set; } 
        public virtual string status_chg_user_code{ get;set; } 
        public virtual string reason_code{ get;set; } 
        public virtual string supply_whse{ get;set; } 
        public virtual string buyer{ get;set; } 
        public virtual string origin{ get;set; } 
        public virtual string tax_code1{ get;set; } 
        public virtual string tax_code2{ get;set; } 
        public virtual string bflush_loc{ get;set; } 
        public virtual string lot_prefix{ get;set; } 
        public virtual string serial_prefix{ get;set; } 
        public virtual string feat_str{ get;set; } 
        public virtual string feat_templ{ get;set; } 
        public virtual string charfld1{ get;set; } 
        public virtual string charfld2{ get;set; } 
        public virtual string charfld3{ get;set; } 
        public virtual string comm_code{ get;set; } 
        public virtual string family_code{ get;set; } 
        public virtual string plan_code{ get;set; } 
        public virtual string revision{ get;set; } 
        public virtual string alt_item{ get;set; } 
        public virtual string weight_units{ get;set; } 
        public virtual string charfld4{ get;set; } 
        public virtual string abc_code{ get;set; } 
        public virtual string p_m_t_code{ get;set; } 
        public virtual string cost_method{ get;set; } 
        public virtual string matl_type{ get;set; } 
        public virtual string feat_type{ get;set; } 
        public virtual string issue_by{ get;set; } 
        public virtual string cost_type{ get;set; } 
        public virtual string prod_type{ get;set; } 
        public virtual string stat{ get;set; } 
        public virtual string auto_job{ get;set; } 
        public virtual string auto_post{ get;set; } 


    }
}